Repository dorvillethiago/projeto-libras, pull requests merged in 2023-09, with the labels that each got.

#9 chore: adicionados os scripts das fontes
  index.css
  index.html
Labels: enhancement

#8 feat: componente da logo
  src/modules/Root/assets/mao_menu.png
  src/modules/Root/components/Logo.tsx
  src/modules/Root/components/Titulo.tsx
Labels: enhancement

#10 chore/ Adicionando imagem background
  assets/background_primario.png
  index.css
Labels: chore

#11 Feat adicionando botão
  src/modules/Root/components/ButtonRedirect.tsx
Labels: enhancement

#12 feat: adicionando tela e modificando componentes para padrão responsivo
  src/modules/Root/Page.tsx
  src/modules/Root/assets/hand_menu.png
  src/modules/Root/assets/mao_menu.png
  src/modules/Root/components/ButtonRedirect.tsx
  src/modules/Root/components/Logo.tsx
  src/modules/Root/components/Title.tsx
  src/modules/Root/components/Titulo.tsx
  src/modules/Root/sessions/ButtonSequence.tsx
  src/modules/Root/sessions/LogoContainer.tsx
  src/utils/NoFlicker.css
  src/utils/getWindowDimensions.ts
Labels: enhancement

#13 fix: corrigido bug de responsividade vertical
  src/modules/Root/Page.tsx
Labels: bug

#15 feat: adicionado componente de backarrow
  src/main.tsx
  src/modules/Credits/assets/arrow.svg
  src/modules/Credits/components/BackArrow.tsx
  src/modules/Root/sessions/ButtonSequence.tsx
Labels: enhancement

#16 chore: implementando alias do diretório utils
  src/modules/Root/components/ButtonRedirect.tsx
  src/modules/Root/components/Logo.tsx
  src/modules/Root/sessions/ButtonSequence.tsx
  vite.config.ts
Labels: enhancement
